### ISSUE TITLE
What's the logic behind applying conv2 twice with no activation in-between

### ISSUE THREAD

**Issue by sakvaua** [bmartacho/WASP#2]
Hi, you apply conv2 twice to each of the x1,x2,x3,x4, where conv2 is a 1x1 conv without any non-linearities in-between the convolutions. Wouldn't that be equivalent to a single 1x1 conv?
Also, your atrous1 conv is also 1x1 and uses 24 dilation, which is kind of extreme for a 1x1 conv.
Thanks!

```
        x1 = self.conv2(x1)
        x2 = self.conv2(x2)
        x3 = self.conv2(x3)
        x4 = self.conv2(x4)
        
        x1 = self.conv2(x1)
        x2 = self.conv2(x2)
        x3 = self.conv2(x3)
        x4 = self.conv2(x4)
```

**Comment by bmartacho** [comment]
During our experiments, several configurations were tested, and we observed a slight gain in performance by performing the 1x1 following the Atrous convolutions.
Different dilation rates were also tested by us and other works with previous ASPP method, achieving maximum performance with the current dilation rates for this configuration.
